name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up Dafny
      uses: dafny-lang/setup-dafny-action@v1
      with:
        dafny-version: "3.4.2"
    - name: Verify Dafny code
      run: dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=2 -p:TestVerifyOverride="verificationLogger:csv"
    - name: Run Tests
      run: dotnet test --verbosity normal
    - name: Self Report
      # Generates a report based on the logged data from verifying itself.
      # This is both a guard against unstable verification and a smoke test of the tool itself.
      run: dotnet run --project src -- summarize-csv-results --max-resource-count 1500000 .
    - name: Stability Analysis
      # Analyzes the stability of verification by running it several
      # more times and calculating statistics
      #
      # Runs Dafny directly because it doesn't seem like we can pass
      # multiple arguments to it through MSBuild.
      run: |
        SDFYS=`find src -name "*.dfy"`
        TDFYS=`find test -name "*.dfy"`
        for seed in 1 2 3 4 5; do
          dafny /compile:0 /timeLimit:30 /verificationLogger:csv /randomSeed:$seed ${SDFYS} ${TDFYS}
        done
        dotnet run --project src -- summarize-csv-results --max-resource-stddev 100000 .
